---
on:
  issues:
    types:
      - opened
      - labeled
  page_build: ~

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "something happened with issue labels and page build"
      - run: jq '.' $GITHUB_EVENT_PATH
