---
on:
  issues:
    types:
      - opened
      - labeled

jobs:
  action-issue-opened-or-labeled:
    runs-on: ubuntu-latest
    steps:
      - run: echo "something happened with issue labels and page build"
      - run: jq '.' $GITHUB_EVENT_PATH
