---
on:
  label:
    types:
      - created
      - edited
      - deleted
jobs:
  action-label-created:
    runs-on: ubuntu-latest
    steps:
      - run: echo "something happened with labels"
      - run: jq '.' $GITHUB_EVENT_PATH
