---
on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
  contents: write

name: Create Release
jobs:
  build:
    name: Build Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: jq '.' $GITHUB_EVENT_PATH
      - run: make build
      - name: Create Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-artifacts
          path: |
            dist/*.zip
            dist/*.zip.asc
            dist/*.zip.md5
            !dist/VERSION
          retention-days: 1

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - id: revision
        run: cat .bumpversion.cfg | grep current_version | awk '{ printf "version=%s\n", $3 }' >> "${GITHUB_OUTPUT}"
      - run: echo "publish with version ${{ steps.revision.outputs.version }}"
      - uses: actions/download-artifact@v3
        with:
          name: release-artifacts
      - run: ls -al dist/
      - name: Create Release
        id: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          name: Release ${{ github.ref }}
          tag_name: ${{ github.ref }}
          draft: true
          files: |
            dist/code-${{ steps.revision.outputs.version }}.zip
            dist/code-${{ steps.revision.outputs.version }}.zip.asc
            dist/code-${{ steps.revision.outputs.version }}.zip.md5
