---
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
      - releases/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "some build"

  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: echo "scan something"

  release:
    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [ build, scan ]
    steps:
      - uses: actions/checkout@v4
      - run: jq '.' $GITHUB_EVENT_PATH
      - id: revision
        run: cat .bumpversion.cfg | grep current_version | awk '{ printf "version=%s\n", $3 }' >> "${GITHUB_OUTPUT}"
      - run: echo "publish with version ${{ steps.revision.outputs.version }}"
